// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sahel.GMAO.Infrastructure.Data;

#nullable disable

namespace Sahel.GMAO.Infrastructure.Migrations
{
    [DbContext(typeof(GmaoDbContext))]
    [Migration("20260420174356_InitialDomain")]
    partial class InitialDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ArticlePdr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("QuantiteEnStock")
                        .HasColumnType("float");

                    b.Property<string>("ReferenceConstructeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SeuilAlerte")
                        .HasColumnType("float");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodeArticle")
                        .IsUnique();

                    b.ToTable("ArticlesPdr");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ConsommableUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticlePdrId")
                        .HasColumnType("int");

                    b.Property<int>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaireApplique")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Quantite")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArticlePdrId");

                    b.HasIndex("DemandeTravailId");

                    b.ToTable("ConsommableUsages");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecutionDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecutionFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceptionPrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeurId")
                        .HasColumnType("int");

                    b.Property<double>("DureeArretProductionHeures")
                        .HasColumnType("float");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("InstructionsPreparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganePartie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCoutMainOeuvre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutOperation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutPieces")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TravailDemande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravailExecute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroDT")
                        .IsUnique();

                    b.ToTable("DemandesTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaracteristiquesTechniques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateMiseEnService")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SousSection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.InterventionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<double>("HeuresTravaillees")
                        .HasColumnType("float");

                    b.Property<int>("IntervenantId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TauxHoraire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeTravailId");

                    b.HasIndex("IntervenantId");

                    b.ToTable("InterventionRoles");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MaintenancePreventive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsignesParticulieres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDerniereRealisation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateProchaineEcheance")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<int>("FrequenceJours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("MaintenancePreventives");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.RapportIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsCorrectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CausesProbables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateIncident")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionIncident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRapport")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RedacteurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroRapport")
                        .IsUnique();

                    b.HasIndex("RedacteurId");

                    b.ToTable("RapportsIncidents");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEditInventory")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewAudit")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ConsommableUsage", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.ArticlePdr", "ArticlePdr")
                        .WithMany("Usages")
                        .HasForeignKey("ArticlePdrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("Consommables")
                        .HasForeignKey("DemandeTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticlePdr");

                    b.Navigation("DemandeTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany("DemandesTravail")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demandeur");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.InterventionRole", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("Intervenants")
                        .HasForeignKey("DemandeTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeTravail");

                    b.Navigation("Intervenant");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MaintenancePreventive", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.RapportIncident", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Redacteur")
                        .WithMany()
                        .HasForeignKey("RedacteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Redacteur");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ArticlePdr", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.Navigation("Consommables");

                    b.Navigation("Intervenants");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.Equipement", b =>
                {
                    b.Navigation("DemandesTravail");
                });
#pragma warning restore 612, 618
        }
    }
}
