// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sahel.GMAO.Infrastructure.Data;

#nullable disable

namespace Sahel.GMAO.Infrastructure.Migrations
{
    [DbContext(typeof(GmaoDbContext))]
    [Migration("20260421103335_AddSpecialtiesAndNotifications")]
    partial class AddSpecialtiesAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ArticlePdr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("QuantiteEnStock")
                        .HasColumnType("float");

                    b.Property<string>("ReferenceConstructeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SeuilAlerte")
                        .HasColumnType("float");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodeArticle")
                        .IsUnique();

                    b.ToTable("ArticlesPdr");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.BonDeConsignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentConsignationId")
                        .HasColumnType("int");

                    b.Property<int?>("AgentDeconsignationId")
                        .HasColumnType("int");

                    b.Property<string>("Atelier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateHeureConsignation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHeureDeconsignation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("MotifConsignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceUtilisateurConsignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceUtilisateurDeconsignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisaConsignation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisaDeconsignation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentConsignationId");

                    b.HasIndex("AgentDeconsignationId");

                    b.HasIndex("DemandeTravailId");

                    b.HasIndex("EquipementId");

                    b.ToTable("BonsDeConsignation");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ConsommableUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticlePdrId")
                        .HasColumnType("int");

                    b.Property<int>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaireApplique")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Quantite")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArticlePdrId");

                    b.HasIndex("DemandeTravailId");

                    b.ToTable("ConsommableUsages");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeFabrication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consignes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DebutTravail")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DegreUrgenceImmediat")
                        .HasColumnType("bit");

                    b.Property<int?>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<string>("DesignationPiece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinTravail")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matiere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NDessin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFabrication")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanJointUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantite")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ReceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferencePiece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<double?>("TempsAlloueHeures")
                        .HasColumnType("float");

                    b.Property<decimal>("TotalCoutMainOeuvre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutOperation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutPieces")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VisaComptabiliteAnalytique")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisaExecution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VisaPreparation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DemandeTravailId");

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroFabrication")
                        .IsUnique();

                    b.ToTable("DemandesFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecutionDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecutionFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceptionPrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeurId")
                        .HasColumnType("int");

                    b.Property<double>("DureeArretProductionHeures")
                        .HasColumnType("float");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("InstructionsPreparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganePartie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialiteRequise")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<double?>("TempsDeMarcheHeures")
                        .HasColumnType("float");

                    b.Property<decimal>("TotalCoutMainOeuvre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutOperation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCoutPieces")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TravailDemande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravailExecute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroDT")
                        .IsUnique();

                    b.ToTable("DemandesTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaracteristiquesTechniques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateMiseEnService")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SousSection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.FicheEntretienPreventif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateFaitLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<int?>("IntervenantId")
                        .HasColumnType("int");

                    b.Property<int?>("MaintenancePreventiveId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodicite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisaIntervenant")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("IntervenantId");

                    b.HasIndex("MaintenancePreventiveId");

                    b.ToTable("FichesEntretienPreventif");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.IntervenantFabrication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoutHoraire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DemandeFabricationId")
                        .HasColumnType("int");

                    b.Property<double>("NombreHeures")
                        .HasColumnType("float");

                    b.Property<string>("NomsEtPrenoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeFabricationId");

                    b.ToTable("IntervenantsFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.InterventionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DemandeTravailId")
                        .HasColumnType("int");

                    b.Property<double>("HeuresTravaillees")
                        .HasColumnType("float");

                    b.Property<int>("IntervenantId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TauxHoraire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeTravailId");

                    b.HasIndex("IntervenantId");

                    b.ToTable("InterventionRoles");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MaintenancePreventive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsignesParticulieres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDerniereRealisation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateProchaineEcheance")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<int>("FrequenceJours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("MaintenancePreventives");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MatiereFabrication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DemandeFabricationId")
                        .HasColumnType("int");

                    b.Property<string>("DesignationMatiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longueur")
                        .HasColumnType("float");

                    b.Property<string>("N_BSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeFabricationId");

                    b.ToTable("MatieresFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.NatureTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NaturesTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.PointageIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("datetime2");

                    b.Property<double>("HeuresTravaillees")
                        .HasColumnType("float");

                    b.Property<int>("InterventionRoleId")
                        .HasColumnType("int");

                    b.Property<int>("JourDuMois")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterventionRoleId");

                    b.ToTable("PointagesIntervention");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.PointageMachineFabrication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AffutageHeures")
                        .HasColumnType("float");

                    b.Property<double>("AutresHeures")
                        .HasColumnType("float");

                    b.Property<int>("DemandeFabricationId")
                        .HasColumnType("int");

                    b.Property<double>("EtauLimeurHeures")
                        .HasColumnType("float");

                    b.Property<double>("FraisageHeures")
                        .HasColumnType("float");

                    b.Property<int>("IntervenantId")
                        .HasColumnType("int");

                    b.Property<double>("SoudureHeures")
                        .HasColumnType("float");

                    b.Property<double>("Tour200Heures")
                        .HasColumnType("float");

                    b.Property<double>("Tour250Heures")
                        .HasColumnType("float");

                    b.Property<double>("Tour300Heures")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DemandeFabricationId");

                    b.HasIndex("IntervenantId");

                    b.ToTable("PointagesMachinesFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.RapportIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsCorrectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CausesProbables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateIncident")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionIncident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRapport")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RedacteurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroRapport")
                        .IsUnique();

                    b.HasIndex("RedacteurId");

                    b.ToTable("RapportsIncidents");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.TacheEntretien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstFait")
                        .HasColumnType("bit");

                    b.Property<int>("FicheEntretienPreventifId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationAEffectuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("SuiteADonner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TempsPrevuHeures")
                        .HasColumnType("float");

                    b.Property<double>("TempsRealiseHeures")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FicheEntretienPreventifId");

                    b.ToTable("TachesEntretien");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEditInventory")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewAudit")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Specialite")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.BonDeConsignation", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.User", "AgentConsignation")
                        .WithMany()
                        .HasForeignKey("AgentConsignationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "AgentDeconsignation")
                        .WithMany()
                        .HasForeignKey("AgentDeconsignationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("BonsDeConsignation")
                        .HasForeignKey("DemandeTravailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentConsignation");

                    b.Navigation("AgentDeconsignation");

                    b.Navigation("DemandeTravail");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ConsommableUsage", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.ArticlePdr", "ArticlePdr")
                        .WithMany("Usages")
                        .HasForeignKey("ArticlePdrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("Consommables")
                        .HasForeignKey("DemandeTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticlePdr");

                    b.Navigation("DemandeTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeFabrication", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("DemandesFabrication")
                        .HasForeignKey("DemandeTravailId");

                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemandeTravail");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany("DemandesTravail")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demandeur");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.FicheEntretienPreventif", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sahel.GMAO.Core.Entities.MaintenancePreventive", "MaintenancePreventive")
                        .WithMany()
                        .HasForeignKey("MaintenancePreventiveId");

                    b.Navigation("Equipement");

                    b.Navigation("Intervenant");

                    b.Navigation("MaintenancePreventive");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.IntervenantFabrication", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeFabrication", "DemandeFabrication")
                        .WithMany("Intervenants")
                        .HasForeignKey("DemandeFabricationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.InterventionRole", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeTravail", "DemandeTravail")
                        .WithMany("Intervenants")
                        .HasForeignKey("DemandeTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeTravail");

                    b.Navigation("Intervenant");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MaintenancePreventive", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.MatiereFabrication", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeFabrication", "DemandeFabrication")
                        .WithMany("MatieresConsommees")
                        .HasForeignKey("DemandeFabricationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeFabrication");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.PointageIntervention", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.InterventionRole", "InterventionRole")
                        .WithMany("Pointages")
                        .HasForeignKey("InterventionRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterventionRole");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.PointageMachineFabrication", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.DemandeFabrication", "DemandeFabrication")
                        .WithMany("PointagesMachines")
                        .HasForeignKey("DemandeFabricationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Intervenant")
                        .WithMany()
                        .HasForeignKey("IntervenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemandeFabrication");

                    b.Navigation("Intervenant");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.RapportIncident", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sahel.GMAO.Core.Entities.User", "Redacteur")
                        .WithMany()
                        .HasForeignKey("RedacteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Redacteur");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.TacheEntretien", b =>
                {
                    b.HasOne("Sahel.GMAO.Core.Entities.FicheEntretienPreventif", "FicheEntretienPreventif")
                        .WithMany("Taches")
                        .HasForeignKey("FicheEntretienPreventifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FicheEntretienPreventif");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.ArticlePdr", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeFabrication", b =>
                {
                    b.Navigation("Intervenants");

                    b.Navigation("MatieresConsommees");

                    b.Navigation("PointagesMachines");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.DemandeTravail", b =>
                {
                    b.Navigation("BonsDeConsignation");

                    b.Navigation("Consommables");

                    b.Navigation("DemandesFabrication");

                    b.Navigation("Intervenants");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.Equipement", b =>
                {
                    b.Navigation("DemandesTravail");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.FicheEntretienPreventif", b =>
                {
                    b.Navigation("Taches");
                });

            modelBuilder.Entity("Sahel.GMAO.Core.Entities.InterventionRole", b =>
                {
                    b.Navigation("Pointages");
                });
#pragma warning restore 612, 618
        }
    }
}
